from selenium.webdriver.common.by import By

# Localizadores
from_field = (By.ID, "from")
to_field = (By.ID, "to")
phone_button = (By.XPATH, "//div[text()='Número de teléfono']")
phone_field = (By.ID, "phone")
code_field = (By.ID, "code")
next_button = (By.XPATH, "//button[@type='submit' and contains(@class, 'full')]")
comfort_tariff = (By.XPATH, "//div[text()='Comfort']")
payment_method_button = (By.XPATH, "//div[contains(@class, 'pp-button') and contains(., 'Método de pago')]")
add_card_option = (By.XPATH, "//div[@class='pp-title' and text()='Agregar tarjeta']")
card_number_field = (By.CSS_SELECTOR, "div.card-number-input input#number")
card_cvv_field = (By.CSS_SELECTOR, "div.card-code-input input#code")
add_card_button = (By.XPATH, "//button[contains(@class, 'button') and contains(@class, 'full') and text()='Agregar']")
close_modal_button = (By.XPATH, "//html/body/div/div/div[2]/div[2]/div[1]/button")
message_for_driver = (By.ID, "comment")
blanket_tissues_toggle = (By.XPATH, "//span[@class='slider round']")
ice_cream_increment_button = (By.CLASS_NAME, "counter-plus")
request_taxi_button = (By.CSS_SELECTOR, "button.button.round")
driver_modal = (By.ID, "driver-info-modal")
driver_info = (By.CLASS_NAME, "driver-info")
separator_element = (By.CSS_SELECTOR, "div.pp-separator[style*='margin-top: 30px']")
payment_method_header = (By.CSS_SELECTOR, "div.head")
pedir_taxi_button = (By.XPATH, "//button[@class='smart-button']//span[text()='Pedir un taxi']")
payment_method_header_close_module = (By.XPATH, "//div[@class='head' and text()='Método de pago']")